# Clippy Configuration

# Warn on pedantic lints
warn-on-all-wildcard-imports = true
disallowed-names = ["foo", "bar", "baz"]

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Type complexity threshold
type-complexity-threshold = 250

# Too many arguments threshold
too-many-arguments-threshold = 10

# Too many lines threshold  
too-many-lines-threshold = 500

